//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.IMAGEN = new HashSet<IMAGEN>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NOMBRE { get; set; }
        public string PRO_MARCA { get; set; }
        public int PRO_STOCK { get; set; }
        public decimal PRO_PRECIO { get; set; }
        public string PRO_DESCRIPCION { get; set; }
        public int TI_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN> IMAGEN { get; set; }
        public virtual TIENDA TIENDA { get; set; }
    }
}
